config/routes.rb
Rails.application.routes.draw do
    resources :gstations

end

app/models/gstation.rb
class Gstation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gstations_controller.rb
class GstationsController < ApplicationController
  before_action :set_gstation, only: [:show, :edit, :update, :destroy]

  # GET /gstations
  # GET /gstations.json
  def index
    @gstations = Gstation.all
  end

  # GET /gstations/1
  # GET /gstations/1.json
  def show
  end

  # GET /gstations/new
  def new
    @gstation = Gstation.new
  end

  # GET /gstations/1/edit
  def edit
  end

  # POST /gstations
  # POST /gstations.json
  def create
    @gstation = Gstation.new(gstation_params)

    respond_to do |format|
      if @gstation.save
        format.html { redirect_to @gstation, notice: 'Gstation was successfully created.' }
        format.json { render :show, status: :created, location: @gstation }
      else
        format.html { render :new }
        format.json { render json: @gstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gstations/1
  # PATCH/PUT /gstations/1.json
  def update
    respond_to do |format|
      if @gstation.update(gstation_params)
        format.html { redirect_to @gstation, notice: 'Gstation was successfully updated.' }
        format.json { render :show, status: :ok, location: @gstation }
      else
        format.html { render :edit }
        format.json { render json: @gstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gstations/1
  # DELETE /gstations/1.json
  def destroy
    @gstation.destroy
    respond_to do |format|
      format.html { redirect_to gstations_url, notice: 'Gstation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gstation
      @gstation = Gstation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gstation_params
      params.require(:gstation).permit(:name, :lat, :lon, :rating, :queue, :gasavail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gstations_helper.rb
module GstationsHelper
end

app/views/gstations/_form.html.erb
<%= form_for(@gstation) do |f| %>
  <% if @gstation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gstation.errors.count, "error") %> prohibited this gstation from being saved:</h2>

      <ul>
      <% @gstation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :queue %><br>
    <%= f.number_field :queue %>
  </div>
  <div class="field">
    <%= f.label :gasavail %><br>
    <%= f.number_field :gasavail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gstations/edit.html.erb
<h1>Editing Gstation</h1>

<%= render 'form' %>

<%= link_to 'Show', @gstation %> |
<%= link_to 'Back', gstations_path %>

app/views/gstations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gstations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Rating</th>
      <th>Queue</th>
      <th>Gasavail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gstations.each do |gstation| %>
      <tr>
        <td><%= gstation.name %></td>
        <td><%= gstation.lat %></td>
        <td><%= gstation.lon %></td>
        <td><%= gstation.rating %></td>
        <td><%= gstation.queue %></td>
        <td><%= gstation.gasavail %></td>
        <td><%= link_to 'Show', gstation %></td>
        <td><%= link_to 'Edit', edit_gstation_path(gstation) %></td>
        <td><%= link_to 'Destroy', gstation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gstation', new_gstation_path %>

app/views/gstations/new.html.erb
<h1>New Gstation</h1>

<%= render 'form' %>

<%= link_to 'Back', gstations_path %>

app/views/gstations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gstation.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @gstation.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @gstation.lon %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @gstation.rating %>
</p>

<p>
  <strong>Queue:</strong>
  <%= @gstation.queue %>
</p>

<p>
  <strong>Gasavail:</strong>
  <%= @gstation.gasavail %>
</p>

<%= link_to 'Edit', edit_gstation_path(@gstation) %> |
<%= link_to 'Back', gstations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zapravka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>